const databaseUrl = process.env.INTEGRATION_DATABASE_URL;
const parsedUrl = databaseUrl ? new URL(databaseUrl) : undefined;
const isolatedSchema = parsedUrl?.searchParams.get("schema");
const ownedStagingSchema = process.env.INTEGRATION_OWNED_SCHEMA;
const dedicatedDatabase = parsedUrl?.pathname.endsWith("_test");
const dedicatedSchema = isolatedSchema === ownedStagingSchema && /^courier_integration_[a-f0-9]{32}_test$/.test(isolatedSchema ?? "");
if (!databaseUrl || (!dedicatedDatabase && !dedicatedSchema)) throw new Error("Integration tests require a dedicated _test database or a runner-owned staging schema");
process.env.DATABASE_URL = databaseUrl;
const redisUrl = process.env.INTEGRATION_REDIS_URL;
if (!redisUrl) throw new Error("INTEGRATION_REDIS_URL must point to a dedicated test Redis instance or database");
process.env.REDIS_URL = redisUrl;
process.env.NODE_ENV = "test";
process.env.JWT_ACCESS_SECRET = "integration-access-secret-at-least-32-characters";
process.env.JWT_REFRESH_SECRET = "integration-refresh-secret-at-least-32-characters";
process.env.FRONTEND_URL = "http://localhost:3000";
process.env.COOKIE_SAME_SITE = "lax";
